# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: employee-web-zuul
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
# HTTP Server (Tomcat) Port
server: 
  port: 8087


# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false