# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: employee-web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
# HTTP Server (Tomcat) Port
server: 
  port: 8087

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false